### ISSUE TITLE
ERROR: Undefined offset: 1 at .../Lychee-Laravel/app/ModelFunctions/AlbumFunctions.php:180

### ISSUE THREAD

**Issue by quigybo** [LycheeOrg/Lychee-Laravel#272]
### Detailed description of the problem
After running a lychee instance for a few days, I can no longer login to the site. It must have been something a user uploaded, but I am not sure what...

The frontend only gives `Server error or API not found` on `Albums::get`. The backend gives:
```
[2019-06-05 14:10:18] local.INFO: select `key`, `value` from `configs`
[2019-06-05 14:10:18] local.INFO: select `key`, `value` from `configs`
[2019-06-05 14:10:18] local.INFO: select `value`, `key` from `configs` where `confidentiality` <= ? [3]
[2019-06-05 14:10:18] local.INFO: select `key`, `value` from `configs`
[2019-06-05 14:10:18] local.INFO: select * from `users` where `users`.`id` = ? limit 1 [0]
[2019-06-05 14:10:18] local.INFO: select `thumbUrl`, `thumb2x`, `type` from `photos` where `album_id` is null order by `takestamp` asc, `photos`.`id` asc limit 3
[2019-06-05 14:10:18] local.INFO: select count(*) as aggregate from `photos` where `album_id` is null limit 3
[2019-06-05 14:10:18] local.INFO: select `thumbUrl`, `thumb2x`, `type` from `photos` where `star` = ? order by `takestamp` asc, `photos`.`id` asc limit 3 [1]
[2019-06-05 14:10:18] local.INFO: select count(*) as aggregate from `photos` where `star` = ? limit 3 [1]
[2019-06-05 14:10:18] local.INFO: select `thumbUrl`, `thumb2x`, `type` from `photos` where `public` = ? order by `takestamp` asc, `photos`.`id` asc limit 3 [1]
[2019-06-05 14:10:18] local.INFO: select count(*) as aggregate from `photos` where `public` = ? limit 3 [1]
[2019-06-05 14:10:18] local.INFO: select `thumbUrl`, `thumb2x`, `type` from `photos` where `created_at` >= ? order by `takestamp` asc, `photos`.`id` asc limit 3 ["2019-06-04 14:10:18"]
[2019-06-05 14:10:18] local.INFO: select count(*) as aggregate from `photos` where `created_at` >= ? limit 3 ["2019-06-04 14:10:18"]
[2019-06-05 14:10:18] local.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /var/www/html/Lychee-Laravel/app/ModelFunctions/AlbumFunctions.php:180)
[stacktrace]
#0 /var/www/html/Lychee-Laravel/app/ModelFunctions/AlbumFunctions.php(180): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/html/L...', 180, Array)
#1 /var/www/html/Lychee-Laravel/app/ModelFunctions/AlbumFunctions.php(237): App\\ModelFunctions\\AlbumFunctions->genSmartAlbumsThumbs(Array, Object(Illuminate\\Database\\Eloquent\\Builder), 'recent')
#2 /var/www/html/Lychee-Laravel/app/Http/Controllers/AlbumsController.php(56): App\\ModelFunctions\\AlbumFunctions->getSmartAlbums()
#3 [internal function]: App\\Http\\Controllers\\AlbumsController->get()
#4 /var/www/html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /var/www/html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('get', Array)
#6 /var/www/html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\AlbumsController), 'get')
#7 /var/www/html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#8 /var/www/html/Lychee-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
...
```

Running the last few SQL statements above on the database gives:
```
mysql> select thumbUrl, thumb2x, type from photos where album_id is null order by takestamp asc, photos.id asc limit 3;
Empty set (0.00 sec)

mysql> select count(*) as aggregate from photos where album_id is null limit 3;
+-----------+
| aggregate |
+-----------+
|         0 |
+-----------+
1 row in set (0.00 sec)

mysql> select thumbUrl, thumb2x, type from photos where star = 1 order by takestamp asc, photos.id asc limit 3;
+---------------------------------------+---------+------------+
| thumbUrl                              | thumb2x | type       |
+---------------------------------------+---------+------------+
| 45c54fad8bb911ab7116e1a0ffedf395.jpeg |       1 | image/jpeg |
| 0f0f4c866c6e8fe5f021a8b0d954f9d1.jpeg |       1 | image/jpeg |
| d3149593162b04c01745e1c14a8590a6.jpeg |       1 | image/jpeg |
+---------------------------------------+---------+------------+
3 rows in set (0.00 sec)

mysql> select count(*) as aggregate from photos where star = 1 limit 3;
+-----------+
| aggregate |
+-----------+
|        23 |
+-----------+
1 row in set (0.00 sec)

mysql> select thumbUrl, thumb2x, type from photos where public = 1 order by takestamp asc, photos.id asc limit 3;
Empty set (0.00 sec)

mysql> select count(*) as aggregate from photos where public = 1 limit 3;
+-----------+
| aggregate |
+-----------+
|         0 |
+-----------+
1 row in set (0.00 sec)

mysql> select thumbUrl, thumb2x, type from photos where created_at >= "2019-06-04 14:10:18" order by takestamp asc, photos.id asc limit 3;
+---------------------------------------+---------+------------+
| thumbUrl                              | thumb2x | type       |
+---------------------------------------+---------+------------+
|                                       |       1 | video/mp4  |
| 40518a84c277e9aeb649d3f9bdb4984f.jpeg |       1 | image/jpeg |
| 820e2f40d8d363ed9442cb667ba41621.jpeg |       1 | image/jpeg |
+---------------------------------------+---------+------------+
3 rows in set (0.00 sec)

mysql> select count(*) as aggregate from photos where created_at >= "2019-06-04 14:10:18" limit 3;
+-----------+
| aggregate |
+-----------+
|       127 |
+-----------+
1 row in set (0.01 sec)
```

### Steps to reproduce the issue
1. Go to landing page
2. Click on signon button
3. Complete login dialog
4. See error `Server error or API not found`

### Output of the diagnostics
```
    Diagnostics
    -----------
    Warning: Dropbox import not working. No property for dropboxKey.

    System Information
    ------------------
    Lychee-front Version:    3.2.14
    Lychee Version (git):    6163679 (master) - Probably more than 30 commits behind master
    DB Version:              040000
    System:                  Linux
    PHP Version:             7.3
    MySQL Version:           8.0.16
    Imagick:                 1
    Imagick Active:          1
    Imagick Version:         1690
    GD Version:              2.2.5

    Config Information
    ------------------
    version:                 040000
    checkForUpdates:         0
    sortingPhotos_col:       takestamp
    sortingPhotos_order:     ASC
    sortingAlbums_col:       description
    sortingAlbums_order:     DESC
    imagick:                 1
    skipDuplicates:          0
    small_max_width:         0
    small_max_height:        360
    medium_max_width:        1920
    medium_max_height:       1080
    lang:                    en
    layout:                  1
    image_overlay:           1
    image_overlay_type:      exif
    default_license:         none
    compression_quality:     90
    full_photo:              1
    deleteImported:          1
    Mod_Frame:               0
    Mod_Frame_refresh:       30000
    landing_page_enable:     0
    landing_owner:           ...
    landing_title:           ...
    landing_subtitle:        
    landing_facebook:        
    landing_flickr:          
    landing_twitter:         
    landing_instagram:       
    landing_youtube:         
    landing_background:      
    thumb_2x:                1
    small_2x:                0
    medium_2x:               0
    site_title:              ...
    site_copyright_enable:   1
    site_copyright_begin:    2019
    site_copyright_end:      2019
```

### Browser and system
* Lychee-Laravel-Docker at commit `a300383f`
* Docker image `bigrob8181/lychee-laravel` v1.30
* Docker image `mysql` v8.0

**Comment by ildyria** [comment]
I'm sooo glad that I added the commit number. `6163679` it is... https://github.com/LycheeOrg/Lychee-Laravel/tree/6163679c8aa25b621647b0c8104b545723028533

**Comment by ildyria** [comment]
By the way you should REALLY update your installation :x

**Comment by ildyria** [comment]
Okay I see what is going wrong:
```
$thumbUrl2x = explode(".", $photo->thumbUrl);
$thumbUrl2x = $thumbUrl2x[0].'@2x.'.$thumbUrl2x[1];
```
So this has been solved with:
https://github.com/LycheeOrg/Lychee-Laravel/pull/243
https://github.com/LycheeOrg/Lychee-Laravel/pull/230

**Comment by quigybo** [comment]
I was going to add the commit to the bug report before realising it was already in the diagnostics into.

I just noticed that `bigrob8181/lychee-laravel` has a new `dev` image uploaded on June 4, I could try that if you think it is safe? Mostly I want to avoid losing any photos.

**Comment by ildyria** [comment]
To be honest, I have no idea. :s
But @roblandry  should be able to answer that. :)

**Comment by quigybo** [comment]
Ok I made a backup and went for it. `bigrob8181/lychee-laravel:dev` (which contains 262dc31) solved my issue, the site is up and running again.

If @roblandry is listening, it may be an idea to make a new stable release of the docker container.
